spring:
  application:
    name: product-storage-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${PWD_POSTGRES}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  scheduling:
    mode: none #optimized, simple, none
    period: 60000 #ms
    priceIncreasePercentage: 10.1
  cache:
    expiration-time: 10 #sec
    initial-capacity: 10

server:
  port: 8080
  servlet:
    context-path: /app

currency-service:
  host: http://localhost:8081
  methods:
    get-currency-rate: /currency-rate
  files:
    default-currency-rates: exchange-rate.json



