spring:
  application:
    name: product-storage-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${PWD_POSTGRES}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  scheduling:
    enabled: false
    period: 60000
    priceIncreasePercentage: 10.1
    optimization: true

server:
  port: 8080
  servlet:
    context-path: /app


